sudo: required
services:
  - docker

before_install:
  - docker build -t matthiasleroy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matthiasleroy/react-test npm test

after_success:
  - docker build -t matthiasleroy/multi-client ./client
  - docker build -t matthiasleroy/multi-nginx ./nginx
  - docker build -t matthiasleroy/multi-server ./server 
  - docker build -t matthiasleroy/multi-worker ./workers

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push matthiasleroy/multi-client
  - docker push matthiasleroy/multi-nginx
  - docker push matthiasleroy/multi-server
  - docker push matthiasleroy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-eu-west-3-975050205795
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

